In [1]:
import pandas as pd
import numpy as np

In [199]:
Data = pd.read_csv(r'D:\Desktop\case1_toyproblem1.csv')

In [195]:
Data.head(10)

         x1        x2        x3        x4        x5          y
0  0.346726  0.523896  0.925441  0.653909  0.594525   4.546008
1  0.269585  0.444897  0.729927  0.735772  0.438677   4.152841
2  0.136124  0.495590  0.518000  0.707346  0.164730   2.000960
3  0.031702  0.359175  0.414278  0.142840  0.821290   0.807743
4  0.624615  0.361940  0.473461  0.351490  0.152737  11.258823
5  0.697099  0.741674  0.540693  0.162128  0.451710   6.259515
6  0.516279  0.492001  0.191299  0.460119  0.261353   6.847218
7  0.442721  0.914298  0.572839  0.327380  0.471881   3.347517
8  0.833360  0.929212  0.072887  0.820272  0.716411   5.846899
9  0.312047  0.674600  0.483009  0.342886  0.698046   3.197331

In [84]:
len_para = len(Data.columns)-1

In [103]:
Data1 = pd.DataFrame()
for i in (0,1,2,-1):
    Data1['%s'%Data.columns[i]] = Data[Data.columns[i]]

In [158]:
0.346726*0.523896/0.925441

0.19628303100467778

In [107]:
Data1.head(10)

         x1        x2        x3          y
0  0.346726  0.523896  0.925441   0.196283
1  0.269585  0.444897  0.729927   0.164314
2  0.136124  0.495590  0.518000   0.130235
3  0.031702  0.359175  0.414278   0.027485
4  0.624615  0.361940  0.473461   0.477491
5  0.697099  0.741674  0.540693   0.956218
6  0.516279  0.492001  0.191299   1.327813
7  0.442721  0.914298  0.572839   0.706619
8  0.833360  0.929212  0.072887  10.624195
9  0.312047  0.674600  0.483009   0.435824

In [200]:
l = len(Data1.columns) - 1
args = [0,1,2]

In [203]:
for i in args:
    globals()['diff_{}'.format(Data.columns[i])] = np.gradient(Data[Data.columns[-1]],Data[Data.columns[i]])

In [206]:
for i in args:
    for j in args:
        globals()['diff_{}_{}'.format(Data.columns[i],Data.columns[j])] = np.gradient(globals()['diff_{}'.format(Data.columns[i])],Data[Data.columns[j]])

In [209]:
for i in args:
    for j in args:
        for k in args:
            globals()['diff_{}_{}_{}'.format(Data.columns[i],Data.columns[j],Data.columns[k])] = np.gradient(globals()['diff_{}_{}'.format(Data.columns[i],Data.columns[j])],Data[Data.columns[k]])

In [210]:
Data1 = pd.DataFrame()
for i in args:
    Data1['%s'%Data.columns[i]] = globals()['{}'.format(Data.columns[i])]
    Data1['diff_%s'%Data.columns[i]] = globals()['diff_{}'.format(Data.columns[i])]
    for j in args:
        Data1['diff_%s_%s'%(Data.columns[i],Data.columns[j])] = globals()['diff_{}_{}'.format(Data.columns[i],Data.columns[j])]
        for k in args:
            Data1['diff_%s_%s_%s'%(Data.columns[i],Data.columns[j],Data.columns[k])] = globals()['diff_{}_{}_{}'.format(Data.columns[i],Data.columns[j],Data.columns[k])]
Data1['%s'%Data.columns[-1]] = Data[Data.columns[-1]]

In [211]:
Data1.to_csv(r'D:\Desktop\toyproblem4.csv',header=True,index=False)

In [85]:
for i in range(len_para):
    globals()['x{}'.format(i+1)] = Data[Data.columns[i]]

In [86]:
y = Data[Data.columns[-1]]

In [87]:
for i in range(len_para):
    globals()['diff_x{}'.format(i+1)] = np.gradient(y,Data[Data.columns[i]])

In [88]:
for i in range(len_para):
    for j in range(len_para):
        globals()['diff_x{}_x{}'.format(i+1,j+1)] = np.gradient(globals()['diff_x{}'.format(i+1)],Data[Data.columns[j]])

In [89]:
for i in range(len_para):
    for j in range(len_para):
        for k in range(len_para):
            globals()['diff_x{}_x{}_x{}'.format(i+1,j+1,k+1)] = np.gradient(globals()['diff_x{}_x{}'.format(i+1,j+1)],Data[Data.columns[k]])

In [179]:
Data1 = pd.DataFrame()
for i in range(len_para):
    Data1['x%d'%(i+1)] = globals()['x{}'.format(i+1)]
    #Data1['diff_x%d'%(i+1)] = globals()['diff_x{}'.format(i+1)]
    #for j in range(len_para):
        #Data1['diff_x%d_x%d'%(i+1,j+1)] = globals()['diff_x{}_x{}'.format(i+1,j+1)]
        #for k in range(len_para):
            #Data1['diff_x%d_x%d_x%d'%(i+1,j+1,k+1)] = globals()['diff_x{}_x{}_x{}'.format(i+1,j+1,k+1)]
Data1['y'] = y

In [180]:
Data1.to_csv(r'D:\Desktop\case1_toyproblem1.csv',header=True,index=False)

In [92]:
len(Data1.columns)

161

In [69]:
def delete_error(a):
    b = []
    for i in range(len(a)):
        if a[i] > 3*min(a):
            b.append(a[i])
    a = list(set(a)-set(b))
    a.remove(max(a))
    return a

In [70]:
b = delete_error(a)

In [71]:
b

[1, 2]

In [63]:
a = set(a)-set(b)

In [65]:
list(a)

[1, 2, 3]

In [72]:
30*9/90

3.0

In [75]:
def trainlist(select, remains, num_selection):
    listcsv = pd.DataFrame()
    index = []
    for i in range(len(remains)):
        index.append(i)
    listcsv['index'] = index
    listcsv['train_arg'] = 0
    listcsv['num_selection'] = num_selection
    for j in range(len(select)):
        listcsv[select[j]] = select[j]
    listcsv['addition_parameter'] = remains
    return listcsv

In [80]:
select = []
remains = Data1.columns[:-1]

In [81]:
a = trainlist(select,remains,10)

In [82]:
a

     index  train_arg  num_selection addition_parameter
0        0          0             10                 x1
1        1          0             10            diff_x1
2        2          0             10         diff_x1_x1
3        3          0             10      diff_x1_x1_x1
4        4          0             10      diff_x1_x1_x2
5        5          0             10      diff_x1_x1_x3
6        6          0             10      diff_x1_x1_x4
7        7          0             10      diff_x1_x1_x5
8        8          0             10      diff_x1_x1_x6
9        9          0             10      diff_x1_x1_x7
10      10          0             10         diff_x1_x2
11      11          0             10      diff_x1_x2_x1
12      12          0             10      diff_x1_x2_x2
13      13          0             10      diff_x1_x2_x3
14      14          0             10      diff_x1_x2_x4
15      15          0             10      diff_x1_x2_x5
16      16          0             10      diff_x1_x2_x6
17      17          0             10      diff_x1_x2_x7
18      18          0             10         diff_x1_x3
19      19          0             10      diff_x1_x3_x1
20      20          0             10      diff_x1_x3_x2
21      21          0             10      diff_x1_x3_x3
22      22          0             10      diff_x1_x3_x4
23      23          0             10      diff_x1_x3_x5
24      24          0             10      diff_x1_x3_x6
25      25          0             10      diff_x1_x3_x7
26      26          0             10         diff_x1_x4
27      27          0             10      diff_x1_x4_x1
28      28          0             10      diff_x1_x4_x2
29      29          0             10      diff_x1_x4_x3
..     ...        ...            ...                ...
376    376          0             10      diff_x7_x4_x2
377    377          0             10      diff_x7_x4_x3
378    378          0             10      diff_x7_x4_x4
379    379          0             10      diff_x7_x4_x5
380    380          0             10      diff_x7_x4_x6
381    381          0             10      diff_x7_x4_x7
382    382          0             10         diff_x7_x5
383    383          0             10      diff_x7_x5_x1
384    384          0             10      diff_x7_x5_x2
385    385          0             10      diff_x7_x5_x3
386    386          0             10      diff_x7_x5_x4
387    387          0             10      diff_x7_x5_x5
388    388          0             10      diff_x7_x5_x6
389    389          0             10      diff_x7_x5_x7
390    390          0             10         diff_x7_x6
391    391          0             10      diff_x7_x6_x1
392    392          0             10      diff_x7_x6_x2
393    393          0             10      diff_x7_x6_x3
394    394          0             10      diff_x7_x6_x4
395    395          0             10      diff_x7_x6_x5
396    396          0             10      diff_x7_x6_x6
397    397          0             10      diff_x7_x6_x7
398    398          0             10         diff_x7_x7
399    399          0             10      diff_x7_x7_x1
400    400          0             10      diff_x7_x7_x2
401    401          0             10      diff_x7_x7_x3
402    402          0             10      diff_x7_x7_x4
403    403          0             10      diff_x7_x7_x5
404    404          0             10      diff_x7_x7_x6
405    405          0             10      diff_x7_x7_x7

[406 rows x 4 columns]